package com.example.util

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flagEmoji: String
) {
    ENGLISH("en", "English", "English", "🇺🇸"),
    BENGALI("bn", "Bengali", "বাংলা", "🇧🇩"),
    HINDI("hi", "Hindi", "हिन्दी", "🇮🇳"),
    SPANISH("es", "Spanish", "Español", "🇪🇸"),
    ARABIC("ar", "Arabic", "العربية", "🇸🇦"),
    FRENCH("fr", "French", "Français", "🇫🇷"),
    GERMAN("de", "German", "Deutsch", "🇩🇪"),
    RUSSIAN("ru", "Russian", "Русский", "🇷🇺"),
    JAPANESE("ja", "Japanese", "日本語", "🇯🇵"),
    PORTUGUESE("pt", "Portuguese", "Português", "🇧🇷"),
    TURKISH("tr", "Turkish", "Türkçe", "🇹🇷"),
    INDONESIAN("id", "Indonesian", "Bahasa Indonesia", "🇮🇩"),
    URDU("ur", "Urdu", "اردو", "🇵🇰"),
    CHINESE("zh", "Chinese", "中文", "🇨🇳")
}

data class AppStrings(
    val appName: String,
    val liveInbox: String,
    val expired: String,
    val activeTempMail: String,
    val copyAddress: String,
    val addressCopied: String,
    val checkNow: String,
    val refresh: String,
    val newMail: String,
    val savedVault: String,
    val credentials: String,
    val tenMinTimer: String,
    val remaining: String,
    val extendTime: String,
    val add10Min: String,
    val add5Min: String,
    val reset10m: String,
    val expiredWarning: String,
    val timeExtended: String,
    val timeReset: String,
    val searchPlaceholder: String,
    val receivedEmails: String,
    val emptyInboxTitle: String,
    val emptyInboxSubtitle: String,
    val sendTestOtpHeader: String,
    val testGoogleOtp: String,
    val testDiscordCode: String,
    val testFacebookAlert: String,
    val testOtpReceived: String,
    val autoSyncIn: String,
    val selectLanguage: String,
    val changeLanguage: String,
    val developerContact: String,
    val createCustomTitle: String,
    val close: String,
    val save: String,
    val delete: String,
    val switchAccount: String,
    val totalAccounts: String,
    val otpCodeFound: String,
    val developerAction: String = "Contact"
)

object LocalizationManager {
    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "LIVE INBOX",
                expired = "EXPIRED",
                activeTempMail = "Active Temporary Mailbox",
                copyAddress = "Copy Address",
                addressCopied = "Email address copied to clipboard!",
                checkNow = "Check Now",
                refresh = "Refresh",
                newMail = "New Mail",
                savedVault = "Saved Vault",
                credentials = "Credentials",
                tenMinTimer = "10-Minute Timer",
                remaining = "remaining",
                extendTime = "Extend Time:",
                add10Min = "+10 Min",
                add5Min = "+5 Min",
                reset10m = "10m",
                expiredWarning = "Mailbox has expired. Tap '+10 Min' to continue or create a new address.",
                timeExtended = "Time extended by %d minutes!",
                timeReset = "Timer reset to %d minutes.",
                searchPlaceholder = "Search subject, sender, or OTP...",
                receivedEmails = "Received Inboxes",
                emptyInboxTitle = "Your Inbox is Waiting",
                emptyInboxSubtitle = "1. Copy your temporary email above and use it for signups or verification.\n2. Incoming emails and OTP codes will arrive here in real-time.",
                sendTestOtpHeader = "⚡ Test instant email reception now:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord Code",
                testFacebookAlert = "Facebook Alert",
                testOtpReceived = "Test verification email received!",
                autoSyncIn = "Auto-sync in %ds",
                selectLanguage = "Select Language / ভাষা নির্বাচন",
                changeLanguage = "Language",
                developerContact = "Developer Support",
                developerAction = "Contact",
                createCustomTitle = "Create Custom Email",
                close = "Close",
                save = "Save",
                delete = "Delete",
                switchAccount = "Switch Mailbox",
                totalAccounts = "Saved Mailboxes",
                otpCodeFound = "OTP Code:"
            )

            AppLanguage.BENGALI -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "লাইভ ইনবক্স",
                expired = "মেয়াদ শেষ",
                activeTempMail = "সক্রিয় অস্থায়ী ইমেইল",
                copyAddress = "কপি করুন",
                addressCopied = "ইমেইল অ্যাড্রেস কপি করা হয়েছে!",
                checkNow = "চেক করুন",
                refresh = "রিফ্রেশ",
                newMail = "নতুন মেইল",
                savedVault = "সেভড ভল্ট",
                credentials = "পাসওয়ার্ড",
                tenMinTimer = "১০ মিনিট মেয়াদ",
                remaining = "বাকি আছে",
                extendTime = "সময় বাড়ান:",
                add10Min = "+১০ মিনিট",
                add5Min = "+৫ মিনিট",
                reset10m = "১০ মি.",
                expiredWarning = "মেয়াদ শেষ হয়েছে। '+১০ মিনিট' চাপুন অথবা নতুন মেইল তৈরি করুন।",
                timeExtended = "সময় +%d মিনিট বাড়ানো হয়েছে!",
                timeReset = "টাইমার %d মিনিটে রিসেট হয়েছে।",
                searchPlaceholder = "বিষয়, প্রেরক বা ওটিপি দিয়ে খুঁজুন...",
                receivedEmails = "প্রাপ্ত ইমেইলসমূহ",
                emptyInboxTitle = "ইনবক্স খালি রয়েছে",
                emptyInboxSubtitle = "১. উপরের ইমেইলটি কপি করে যেকোনো সাইটে সাইন-আপে দিন।\n২. ওটিপি বা ভেরিফিকেশন লিঙ্ক স্বয়ংক্রিয়ভাবে এখানে চলে আসবে।",
                sendTestOtpHeader = "⚡ এখনই টেস্ট ইমেইল গ্রহণ করে পরীক্ষা করুন:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord Code",
                testFacebookAlert = "Facebook",
                testOtpReceived = "টেস্ট ভেরিফিকেশন কোড এসে গেছে!",
                autoSyncIn = "%d সেকেন্ডে অটো-সিঙ্ক",
                selectLanguage = "ভাষা নির্বাচন করুন",
                changeLanguage = "ভাষা / Language",
                developerContact = "ডেভেলপার সাপোর্ট",
                developerAction = "যোগাযোগ",
                createCustomTitle = "কাস্টম ইমেইল তৈরি",
                close = "বন্ধ করুন",
                save = "সংরক্ষণ",
                delete = "মুছে ফেলুন",
                switchAccount = "মেইল পরিবর্তন",
                totalAccounts = "সংরক্ষিত মেইলবক্স",
                otpCodeFound = "ওটিপি কোড:"
            )

            AppLanguage.HINDI -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "लाइव इनबॉक्स",
                expired = "समाप्त",
                activeTempMail = "सक्रिय अस्थायी ईमेल",
                copyAddress = "कॉपी करें",
                addressCopied = "ईमेल पता कॉपी किया गया!",
                checkNow = "जांचें",
                refresh = "रिफ्रेश",
                newMail = "नया मेल",
                savedVault = "वॉल्ट",
                credentials = "पासवर्ड",
                tenMinTimer = "10 मिनट टाइमर",
                remaining = "शेष",
                extendTime = "समय बढ़ाएं:",
                add10Min = "+10 मिनट",
                add5Min = "+5 मिनट",
                reset10m = "10 मि.",
                expiredWarning = "समय समाप्त हो गया है। जारी रखने के लिए '+10 मिनट' दबाएं।",
                timeExtended = "समय %d मिनट बढ़ा दिया गया!",
                timeReset = "टाइमर %d मिनट पर रीसेट किया गया।",
                searchPlaceholder = "विषय, प्रेषक या ओटीपी खोजें...",
                receivedEmails = "प्राप्त ईमेल",
                emptyInboxTitle = "इनबॉक्स खाली है",
                emptyInboxSubtitle = "1. ऊपर दिए गए ईमेल को कॉपी करें और साइन-अप में उपयोग करें।\n2. ओटीपी कोड यहां तुरंत आ जाएगा।",
                sendTestOtpHeader = "⚡ तुरंत टेस्ट ईमेल प्राप्त करें:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord Code",
                testFacebookAlert = "Facebook",
                testOtpReceived = "टेस्ट ईमेल प्राप्त हुआ!",
                autoSyncIn = "%d सेकंड में ऑटो-सिंक",
                selectLanguage = "भाषा चुनें",
                changeLanguage = "भाषा",
                developerContact = "डेवलपर सहायता",
                createCustomTitle = "कस्टम ईमेल बनाएं",
                close = "बंद करें",
                save = "सहेजें",
                delete = "हटाएं",
                switchAccount = "ईमेल बदलें",
                totalAccounts = "सहेजे गए ईमेल",
                otpCodeFound = "ओटीपी कोड:"
            )

            AppLanguage.SPANISH -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "BANDEJA EN VIVO",
                expired = "EXPIRADO",
                activeTempMail = "Bandeja Temporal Activa",
                copyAddress = "Copiar",
                addressCopied = "¡Correo copiado al portapapeles!",
                checkNow = "Verificar",
                refresh = "Actualizar",
                newMail = "Nuevo Correo",
                savedVault = "Bóveda",
                credentials = "Credenciales",
                tenMinTimer = "Temporizador 10 Min",
                remaining = "restante",
                extendTime = "Extender:",
                add10Min = "+10 Min",
                add5Min = "+5 Min",
                reset10m = "10m",
                expiredWarning = "El correo ha expirado. Presione '+10 Min' para continuar.",
                timeExtended = "¡Tiempo extendido en %d minutos!",
                timeReset = "Temporizador reiniciado a %d minutos.",
                searchPlaceholder = "Buscar asunto, remitente o OTP...",
                receivedEmails = "Correos Recibidos",
                emptyInboxTitle = "Bandeja de Entrada Vacía",
                emptyInboxSubtitle = "1. Copie el correo arriba y úselo para registrarse.\n2. Los códigos OTP y enlaces llegarán en tiempo real.",
                sendTestOtpHeader = "⚡ Probar recepción de correo ahora:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Código Discord",
                testFacebookAlert = "Alerta Facebook",
                testOtpReceived = "¡Correo de prueba recibido!",
                autoSyncIn = "Sincronización en %ds",
                selectLanguage = "Seleccionar Idioma",
                changeLanguage = "Idioma",
                developerContact = "Soporte",
                createCustomTitle = "Crear Correo Personalizado",
                close = "Cerrar",
                save = "Guardar",
                delete = "Eliminar",
                switchAccount = "Cambiar Cuenta",
                totalAccounts = "Cuentas Guardadas",
                otpCodeFound = "Código OTP:"
            )

            AppLanguage.ARABIC -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "صندوق بريد مباشر",
                expired = "منتهي الصلاحية",
                activeTempMail = "البريد المؤقت النشط",
                copyAddress = "نسخ البريد",
                addressCopied = "تم نسخ عنوان البريد الإلكتروني!",
                checkNow = "فحص الآن",
                refresh = "تحديث",
                newMail = "بريد جديد",
                savedVault = "الخزنة",
                credentials = "بيانات الاعتماد",
                tenMinTimer = "مؤقت 10 دقائق",
                remaining = "متبقي",
                extendTime = "تمديد الوقت:",
                add10Min = "+10 دقيقة",
                add5Min = "+5 دقيقة",
                reset10m = "10د",
                expiredWarning = "انتهت صلاحية البريد. اضغط '+10 دقيقة' للمتابعة.",
                timeExtended = "تم تمديد الوقت بمقدار %d دقائق!",
                timeReset = "تمت إعادة ضبط المؤقت إلى %d دقائق.",
                searchPlaceholder = "بحث في الموضوع أو المرسل أو رمز التحقق...",
                receivedEmails = "الرسائل المستلمة",
                emptyInboxTitle = "صندوق الوارد فارغ",
                emptyInboxSubtitle = "1. انسخ البريد أعلاه واستخدمه للتسجيل.\n2. ستصلك رسائل التحقق ورموز OTP فوراً هنا.",
                sendTestOtpHeader = "⚡ إرسال بريد تجريبي الآن:",
                testGoogleOtp = "رمز Google",
                testDiscordCode = "رمز Discord",
                testFacebookAlert = "تنبيه Facebook",
                testOtpReceived = "تم استلام بريد التحقق التجريبي!",
                autoSyncIn = "مزامنة خلال %d ث",
                selectLanguage = "اختر اللغة",
                changeLanguage = "اللغة",
                developerContact = "دعم المطور",
                createCustomTitle = "إنشاء بريد مخصص",
                close = "إغلاق",
                save = "حفظ",
                delete = "حذف",
                switchAccount = "تبديل البريد",
                totalAccounts = "الحسابات المحفوظة",
                otpCodeFound = "رمز التحقق OTP:"
            )

            AppLanguage.FRENCH -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "BOÎTE EN DIRECT",
                expired = "EXPIRÉ",
                activeTempMail = "Boîte Temporaire Active",
                copyAddress = "Copier",
                addressCopied = "Adresse e-mail copiée !",
                checkNow = "Vérifier",
                refresh = "Actualiser",
                newMail = "Nouveau",
                savedVault = "Coffre-fort",
                credentials = "Identifiants",
                tenMinTimer = "Minuteur 10 Min",
                remaining = "restant",
                extendTime = "Prolonger :",
                add10Min = "+10 Min",
                add5Min = "+5 Min",
                reset10m = "10m",
                expiredWarning = "La boîte a expiré. Appuyez sur '+10 Min' pour continuer.",
                timeExtended = "Temps prolongé de %d minutes !",
                timeReset = "Minuteur réinitialisé à %d minutes.",
                searchPlaceholder = "Rechercher un objet, expéditeur ou OTP...",
                receivedEmails = "E-mails Reçus",
                emptyInboxTitle = "Boîte de réception vide",
                emptyInboxSubtitle = "1. Copiez l'adresse ci-dessus pour vos inscriptions.\n2. Les codes OTP et e-mails arriveront en direct.",
                sendTestOtpHeader = "⚡ Tester la réception d'un e-mail :",
                testGoogleOtp = "OTP Google",
                testDiscordCode = "Code Discord",
                testFacebookAlert = "Alerte Facebook",
                testOtpReceived = "E-mail de test reçu avec succès !",
                autoSyncIn = "Synchronisation dans %ds",
                selectLanguage = "Choisir la langue",
                changeLanguage = "Langue",
                developerContact = "Support Développeur",
                createCustomTitle = "Créer un e-mail personnalisé",
                close = "Fermer",
                save = "Enregistrer",
                delete = "Supprimer",
                switchAccount = "Changer de compte",
                totalAccounts = "Boîtes enregistrées",
                otpCodeFound = "Code OTP :"
            )

            AppLanguage.GERMAN -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "LIVE POSTEINGANG",
                expired = "ABGELAUFEN",
                activeTempMail = "Aktives temporäres Postfach",
                copyAddress = "Kopieren",
                addressCopied = "E-Mail-Adresse kopiert!",
                checkNow = "Prüfen",
                refresh = "Aktualisieren",
                newMail = "Neue E-Mail",
                savedVault = "Tresor",
                credentials = "Zugangsdaten",
                tenMinTimer = "10-Minuten-Timer",
                remaining = "verbleibend",
                extendTime = "Verlängern:",
                add10Min = "+10 Min",
                add5Min = "+5 Min",
                reset10m = "10m",
                expiredWarning = "Postfach ist abgelaufen. Tippen Sie auf '+10 Min' zum Verlängern.",
                timeExtended = "Zeit um %d Minuten verlängert!",
                timeReset = "Timer auf %d Minuten zurückgesetzt.",
                searchPlaceholder = "Betreff, Absender oder OTP suchen...",
                receivedEmails = "Empfangene E-Mails",
                emptyInboxTitle = "Posteingang ist leer",
                emptyInboxSubtitle = "1. Kopieren Sie die obige E-Mail für Anmeldungen.\n2. OTP-Codes und Verifizierungs-E-Mails erscheinen sofort.",
                sendTestOtpHeader = "⚡ Jetzt Test-E-Mail empfangen:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord Code",
                testFacebookAlert = "Facebook Benachrichtigung",
                testOtpReceived = "Test-E-Mail erfolgreich empfangen!",
                autoSyncIn = "Auto-Sync in %ds",
                selectLanguage = "Sprache auswählen",
                changeLanguage = "Sprache",
                developerContact = "Entwickler-Support",
                createCustomTitle = "Eigene E-Mail erstellen",
                close = "Schließen",
                save = "Speichern",
                delete = "Löschen",
                switchAccount = "Konto wechseln",
                totalAccounts = "Gespeicherte Postfächer",
                otpCodeFound = "OTP-Code:"
            )

            AppLanguage.RUSSIAN -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "АКТИВНЫЙ ВХОДЯЩИЙ",
                expired = "ИСТЕКЛО",
                activeTempMail = "Активный временный ящик",
                copyAddress = "Копировать",
                addressCopied = "Адрес электронной почты скопирован!",
                checkNow = "Проверить",
                refresh = "Обновить",
                newMail = "Новая почта",
                savedVault = "Хранилище",
                credentials = "Учетные данные",
                tenMinTimer = "10-минутный таймер",
                remaining = "осталось",
                extendTime = "Продлить:",
                add10Min = "+10 мин",
                add5Min = "+5 мин",
                reset10m = "10м",
                expiredWarning = "Срок действия истек. Нажмите '+10 мин', чтобы продолжить.",
                timeExtended = "Время продлено на %d мин!",
                timeReset = "Таймер сброшен на %d мин.",
                searchPlaceholder = "Поиск по теме, отправителю или коду...",
                receivedEmails = "Полученные письма",
                emptyInboxTitle = "Входящие пусты",
                emptyInboxSubtitle = "1. Скопируйте адрес выше и используйте для регистрации.\n2. Коды OTP и письма появятся мгновенно.",
                sendTestOtpHeader = "⚡ Проверить получение письма:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Код Discord",
                testFacebookAlert = "Facebook",
                testOtpReceived = "Тестовое письмо получено!",
                autoSyncIn = "Синхронизация через %dс",
                selectLanguage = "Выбрать язык",
                changeLanguage = "Язык",
                developerContact = "Поддержка",
                createCustomTitle = "Создать свой адрес",
                close = "Закрыть",
                save = "Сохранить",
                delete = "Удалить",
                switchAccount = "Сменить ящик",
                totalAccounts = "Сохраненные ящики",
                otpCodeFound = "Код OTP:"
            )

            AppLanguage.JAPANESE -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "受信トレイ（ライブ）",
                expired = "期限切れ",
                activeTempMail = "使用中の使い捨てメール",
                copyAddress = "アドレスをコピー",
                addressCopied = "メールアドレスをコピーしました！",
                checkNow = "今すぐ確認",
                refresh = "更新",
                newMail = "新規メール",
                savedVault = "保存済み保管庫",
                credentials = "認証情報",
                tenMinTimer = "10分タイマー",
                remaining = "残り",
                extendTime = "時間を延長:",
                add10Min = "+10分",
                add5Min = "+5分",
                reset10m = "10分",
                expiredWarning = "メールボックスの期限が切れました。「+10分」で延長できます。",
                timeExtended = "%d分延長しました！",
                timeReset = "タイマーを%d分にリセットしました。",
                searchPlaceholder = "件名、送信者、OTPコードを検索...",
                receivedEmails = "受信メール一覧",
                emptyInboxTitle = "受信トレイは空です",
                emptyInboxSubtitle = "1. 上記のアドレスをコピーして登録に使用してください。\n2. 認証コードやメールがリアルタイムで届きます。",
                sendTestOtpHeader = "⚡ テストメールの受信を確認:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord コード",
                testFacebookAlert = "Facebook 通知",
                testOtpReceived = "テスト認証メールを受信しました！",
                autoSyncIn = "%d秒後に自動同期",
                selectLanguage = "言語を選択",
                changeLanguage = "言語設定",
                developerContact = "開発者サポート",
                createCustomTitle = "カスタムメールを作成",
                close = "閉じる",
                save = "保存",
                delete = "削除",
                switchAccount = "アカウント切替",
                totalAccounts = "保存済みメール",
                otpCodeFound = "OTP認証コード:"
            )

            AppLanguage.PORTUGUESE -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "CAIXA DE ENTRADA",
                expired = "EXPIRADO",
                activeTempMail = "E-mail Temporário Ativo",
                copyAddress = "Copiar",
                addressCopied = "E-mail copiado com sucesso!",
                checkNow = "Verificar",
                refresh = "Atualizar",
                newMail = "Novo E-mail",
                savedVault = "Cofre",
                credentials = "Credenciais",
                tenMinTimer = "Temporizador de 10 Min",
                remaining = "restante",
                extendTime = "Estender:",
                add10Min = "+10 Min",
                add5Min = "+5 Min",
                reset10m = "10m",
                expiredWarning = "O e-mail expirou. Toque em '+10 Min' para estender.",
                timeExtended = "Tempo estendido em %d minutos!",
                timeReset = "Temporizador redefinido para %d minutos.",
                searchPlaceholder = "Pesquisar assunto, remetente ou OTP...",
                receivedEmails = "E-mails Recebidos",
                emptyInboxTitle = "Sua caixa está vazia",
                emptyInboxSubtitle = "1. Copie o endereço acima para se cadastrar.\n2. Códigos OTP e links chegarão aqui em tempo real.",
                sendTestOtpHeader = "⚡ Testar recebimento de e-mail agora:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Código Discord",
                testFacebookAlert = "Alerta Facebook",
                testOtpReceived = "E-mail de teste recebido com sucesso!",
                autoSyncIn = "Sincronização em %ds",
                selectLanguage = "Selecionar Idioma",
                changeLanguage = "Idioma",
                developerContact = "Suporte",
                createCustomTitle = "Criar E-mail Personalizado",
                close = "Fechar",
                save = "Salvar",
                delete = "Excluir",
                switchAccount = "Trocar de Conta",
                totalAccounts = "Contas Salvas",
                otpCodeFound = "Código OTP:"
            )

            AppLanguage.TURKISH -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "CANLI GELEN KUTUSU",
                expired = "SÜRESİ DOLDU",
                activeTempMail = "Aktif Geçici E-posta",
                copyAddress = "Kopyala",
                addressCopied = "E-posta adresi kopyalandı!",
                checkNow = "Kontrol Et",
                refresh = "Yenile",
                newMail = "Yeni E-posta",
                savedVault = "Kasa",
                credentials = "Giriş Bilgileri",
                tenMinTimer = "10 Dakikalık Sayaç",
                remaining = "kaldı",
                extendTime = "Süreyi Uzat:",
                add10Min = "+10 Dk",
                add5Min = "+5 Dk",
                reset10m = "10dk",
                expiredWarning = "Posta kutusunun süresi doldu. Devam etmek için '+10 Dk' butonuna dokunun.",
                timeExtended = "Süre %d dakika uzatıldı!",
                timeReset = "Sayaç %d dakikaya sıfırlandı.",
                searchPlaceholder = "Konu, gönderen veya OTP ara...",
                receivedEmails = "Gelen E-postalar",
                emptyInboxTitle = "Gelen kutunuz boş",
                emptyInboxSubtitle = "1. Yukarıdaki adresi kopyalayıp kayıt için kullanın.\n2. OTP kodları ve doğrulama e-postaları anında gelecektir.",
                sendTestOtpHeader = "⚡ Test e-postasını şimdi alın:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Discord Kodu",
                testFacebookAlert = "Facebook Bildirimi",
                testOtpReceived = "Test doğrulama e-postası alındı!",
                autoSyncIn = "%d sn içinde senkronize edilecek",
                selectLanguage = "Dil Seçin",
                changeLanguage = "Dil",
                developerContact = "Geliştirici Desteği",
                createCustomTitle = "Özel E-posta Oluştur",
                close = "Kapat",
                save = "Kaydet",
                delete = "Sil",
                switchAccount = "Hesap Değiştir",
                totalAccounts = "Kayıtlı E-postalar",
                otpCodeFound = "OTP Kodu:"
            )

            AppLanguage.INDONESIAN -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "KOTAK MASUK LANGSUNG",
                expired = "KADALUWARSA",
                activeTempMail = "Email Sementara Aktif",
                copyAddress = "Salin Alamat",
                addressCopied = "Alamat email berhasil disalin!",
                checkNow = "Periksa Sekarang",
                refresh = "Segarkan",
                newMail = "Email Baru",
                savedVault = "Brankas",
                credentials = "Kredensial",
                tenMinTimer = "Pengatur Waktu 10 Menit",
                remaining = "tersisa",
                extendTime = "Perpanjang Waktu:",
                add10Min = "+10 Mnt",
                add5Min = "+5 Mnt",
                reset10m = "10m",
                expiredWarning = "Kotak masuk telah kadaluwarsa. Ketuk '+10 Mnt' untuk melanjutkan.",
                timeExtended = "Waktu diperpanjang %d menit!",
                timeReset = "Waktu disetel ulang ke %d menit.",
                searchPlaceholder = "Cari subjek, pengirim, atau OTP...",
                receivedEmails = "Email Masuk",
                emptyInboxTitle = "Kotak Masuk Kosong",
                emptyInboxSubtitle = "1. Salin email di atas dan gunakan untuk pendaftaran.\n2. Kode OTP dan email verifikasi akan masuk secara real-time.",
                sendTestOtpHeader = "⚡ Uji penerimaan email sekarang:",
                testGoogleOtp = "Google OTP",
                testDiscordCode = "Kode Discord",
                testFacebookAlert = "Notifikasi Facebook",
                testOtpReceived = "Email verifikasi uji coba diterima!",
                autoSyncIn = "Sinkronisasi dalam %dd",
                selectLanguage = "Pilih Bahasa",
                changeLanguage = "Bahasa",
                developerContact = "Bantuan Pengembang",
                createCustomTitle = "Buat Email Kustom",
                close = "Tutup",
                save = "Simpan",
                delete = "Hapus",
                switchAccount = "Ganti Email",
                totalAccounts = "Email Tersimpan",
                otpCodeFound = "Kode OTP:"
            )

            AppLanguage.URDU -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "لائیو ان باکس",
                expired = "میعاد ختم",
                activeTempMail = "فعال عارضی ای میل",
                copyAddress = "کاپی کریں",
                addressCopied = "ای میل ایڈریس کاپی ہو گیا!",
                checkNow = "چیک کریں",
                refresh = "ریفریش",
                newMail = "نیا میل",
                savedVault = "والٹ",
                credentials = "پاس ورڈ",
                tenMinTimer = "10 منٹ کا ٹائمر",
                remaining = "باقی",
                extendTime = "وقت بڑھائیں:",
                add10Min = "+10 منٹ",
                add5Min = "+5 منٹ",
                reset10m = "10 منٹ",
                expiredWarning = "میعاد ختم ہو چکی ہے۔ جاری رکھنے کے لیے '+10 منٹ' دبائیں۔",
                timeExtended = "وقت %d منٹ بڑھا دیا گیا!",
                timeReset = "ٹائمر %d منٹ پر ری سیٹ ہو گیا۔",
                searchPlaceholder = "موضوع، بھیجنے والے یا OTP سے تلاش کریں...",
                receivedEmails = "موصول شدہ ای میلز",
                emptyInboxTitle = "ان باکس خالی ہے",
                emptyInboxSubtitle = "1. اوپر دیا گیا ای میل کاپی کریں اور سائن اپ میں استعمال کریں۔\n2. OTP کوڈ فوری طور پر یہاں موصول ہو جائے گا۔",
                sendTestOtpHeader = "⚡ ابھی ٹیسٹ ای میل موصول کریں:",
                testGoogleOtp = "گوگل OTP",
                testDiscordCode = "ڈسکارڈ کوڈ",
                testFacebookAlert = "فیس بک الرٹ",
                testOtpReceived = "ٹیسٹ ای میل موصول ہو گئی!",
                autoSyncIn = "%d سیکنڈ میں خودکار مطابقت پذیری",
                selectLanguage = "زبان منتخب کریں",
                changeLanguage = "زبان",
                developerContact = "ڈویلپر سپورٹ",
                createCustomTitle = "اپنی مرضی کا ای میل بنائیں",
                close = "بند کریں",
                save = "محفوظ کریں",
                delete = "حذف کریں",
                switchAccount = "ای میل تبدیل کریں",
                totalAccounts = "محفوظ ای میلز",
                otpCodeFound = "OTP کوڈ:"
            )

            AppLanguage.CHINESE -> AppStrings(
                appName = "Temp Mail Pro",
                liveInbox = "实时收件箱",
                expired = "已过期",
                activeTempMail = "当前临时邮箱",
                copyAddress = "复制邮箱",
                addressCopied = "邮箱地址已复制到剪贴板！",
                checkNow = "立即检查",
                refresh = "刷新",
                newMail = "新建邮箱",
                savedVault = "邮箱保管库",
                credentials = "登录凭证",
                tenMinTimer = "10分钟倒计时",
                remaining = "剩余",
                extendTime = "延长时长:",
                add10Min = "+10分钟",
                add5Min = "+5分钟",
                reset10m = "10分",
                expiredWarning = "邮箱已过期。点击“+10分钟”即可继续使用或创建新邮箱。",
                timeExtended = "时长已延长 %d 分钟！",
                timeReset = "倒计时已重置为 %d 分钟。",
                searchPlaceholder = "搜索主题、发件人或验证码...",
                receivedEmails = "已收邮件",
                emptyInboxTitle = "收件箱暂无邮件",
                emptyInboxSubtitle = "1. 复制上方临时邮箱用于网站注册。\n2. 验证码及邮件将实时自动送达。",
                sendTestOtpHeader = "⚡ 立即测试接收邮件：",
                testGoogleOtp = "Google 验证码",
                testDiscordCode = "Discord 验证码",
                testFacebookAlert = "Facebook 提醒",
                testOtpReceived = "已收到测试验证码邮件！",
                autoSyncIn = "%d秒后自动刷新",
                selectLanguage = "选择语言",
                changeLanguage = "语言切换",
                developerContact = "开发者支持",
                createCustomTitle = "自定义邮箱",
                close = "关闭",
                save = "保存",
                delete = "删除",
                switchAccount = "切换邮箱",
                totalAccounts = "已存邮箱",
                otpCodeFound = "OTP 验证码:"
            )
        }
    }
}
